/private/tmp/ghc-OBlqwe/ghc-7.8.3/Ghcsource/inplace/lib/bin/haddock -B/private/tmp/ghc-OBlqwe/ghc-7.8.3/Ghcsource/inplace/lib -l/private/tmp/ghc-OBlqwe/ghc-7.8.3/Ghcsource/inplace/lib --odir=libraries/template-haskell/dist-install/doc/html/template-haskell --no-tmp-comp-dir --dump-interface=libraries/template-haskell/dist-install/doc/html/template-haskell/template-haskell.haddock --html --hoogle --title=template-haskell-2.9.0.0: Support library for Template Haskell --prologue=libraries/template-haskell/dist-install/haddock-prologue.txt --read-interface=../base-4.7.0.1,../base-4.7.0.1/src/%{MODULE/./-}.html#%{NAME},libraries/base/dist-install/doc/html/base/base.haddock --read-interface=../containers-0.5.5.1,../containers-0.5.5.1/src/%{MODULE/./-}.html#%{NAME},libraries/containers/dist-install/doc/html/containers/containers.haddock --read-interface=../pretty-1.1.1.1,../pretty-1.1.1.1/src/%{MODULE/./-}.html#%{NAME},libraries/pretty/dist-install/doc/html/pretty/pretty.haddock --optghc=-hisuf --optghc=dyn_hi --optghc=-osuf --optghc=dyn_o --optghc=-hcsuf --optghc=dyn_hc --optghc=-fPIC --optghc=-dynamic --optghc=-H32m --optghc=-O --optghc=-package-name --optghc=template-haskell-2.9.0.0 --optghc=-hide-all-packages --optghc=-i --optghc=-ilibraries/template-haskell/. --optghc=-ilibraries/template-haskell/dist-install/build --optghc=-ilibraries/template-haskell/dist-install/build/autogen --optghc=-Ilibraries/template-haskell/dist-install/build --optghc=-Ilibraries/template-haskell/dist-install/build/autogen --optghc=-Ilibraries/template-haskell/. --optghc=-optP-include --optghc=-optPlibraries/template-haskell/dist-install/build/autogen/cabal_macros.h --optghc=-package --optghc=base-4.7.0.1 --optghc=-package --optghc=containers-0.5.5.1 --optghc=-package --optghc=pretty-1.1.1.1 --optghc=-Wall --optghc=-package-name --optghc=template-haskell --optghc=-XHaskell2010 --optghc=-O2 --optghc=-no-user-package-db --optghc=-rtsopts --optghc=-odir --optghc=libraries/template-haskell/dist-install/build --optghc=-hidir --optghc=libraries/template-haskell/dist-install/build --optghc=-stubdir --optghc=libraries/template-haskell/dist-install/build libraries/template-haskell/./Language/Haskell/TH.hs libraries/template-haskell/./Language/Haskell/TH/Lib.hs libraries/template-haskell/./Language/Haskell/TH/Ppr.hs libraries/template-haskell/./Language/Haskell/TH/PprLib.hs libraries/template-haskell/./Language/Haskell/TH/Quote.hs libraries/template-haskell/./Language/Haskell/TH/Syntax.hs +RTS -tlibraries/template-haskell/dist-install/doc/html/template-haskell/template-haskell.haddock.t --machine-readable 
 [("bytes allocated", "1035993352")
 ,("num_GCs", "1594")
 ,("average_bytes_used", "19136444")
 ,("max_bytes_used", "47634576")
 ,("num_byte_usage_samples", "8")
 ,("peak_megabytes_allocated", "123")
 ,("init_cpu_seconds", "0.00")
 ,("init_wall_seconds", "0.00")
 ,("mutator_cpu_seconds", "0.43")
 ,("mutator_wall_seconds", "0.46")
 ,("GC_cpu_seconds", "0.52")
 ,("GC_wall_seconds", "0.56")
 ]
